### ISSUE TITLE
Option to disable motion sensors 

### ISSUE THREAD

**Issue by ghost** [gozoinks/homebridge-camera-ffmpeg-ufv#21]
While the addition of motion sensors is a much welcome addition, is there a way to disable them. I am currently using [homebridge-motionsensor-web ](https://github.com/pmoon00/homebridge-motionsensor-web)for UFV, It works by reading UFV motion logs so there is no time restrictions betweens alerts.

**Comment by adrum** [comment]
@R-OG I created a pull request that makes disabling the motion sensors "opt-in."  This should give you the flexibility you need. I like the implementation in your original message since it's probably quicker and doesn't come with limitations, but it seems the approach used in this project is a bit more "user-friendly". 

Hopefully Ubiquiti implements some sort of MQTT based API in Unifi Protect to allow real-time status changes on motions sensors in the future.
